# Generated by Django 2.0.6 on 2019-03-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlankLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'blank_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloorBuliding',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'floor_buliding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'seat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeatDate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('floor_id', models.IntegerField()),
                ('seat_id', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'seat_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDefaultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('conut', models.IntegerField()),
            ],
            options={
                'db_table': 'user_default_record',
                'managed': False,
            },
        ),
    ]
